# Generated by Django 4.0.1 on 2022-02-12 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='tag_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
